spring:
    # DruidDataSource
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: admin

#mybatis
mybatis-plus:
  mapper-locations: classpath*:com/siyuan/intplatform/web/dao/**Dao.xml
#  mapper-locations: classpath:mapper/**Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.siyuan.intplatform.web.entity.**
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";4:"该类型为未设置主键类型";5:"字符串全局唯一ID"
    id-type: 5
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl #打印sql语句,调试用
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
    log-prefix: dao.

